spring:
  application:
    name: Cloudmerce

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    open-in-view: false

server:
  port: 8080
  error:
    include-binding-errors: always

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
      expiration-time-min: 1440

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  s3:
    region: region
    bucketName: bucket
